version: "3"

services:
  web:
    container_name: fuel_web
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www
    ports:
      - "8080:80"
    links:
      - app
  app:
    container_name: fuel_app
    build:
      context: ./php7/
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www
      - ./tmp/mysqld:/var/run/mysqld
    links:
      - mysql
      - redis
  mysql:
    image: mysql:5.7
    platform: linux/x86_64
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - ./docker/mysql/volumes:/var/lib/mysql
      - ./docker/mysql:/var/run/mysqld/mysqld.sock
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - mysql
    ports:
      - 4040:80
    volumes:
      - ./docker/phpmyadmin/sessions:/sessions
  redis:
    container_name: fuel_redis
    restart: always
    image: redis:latest
    volumes:
      - ./redis:/data
    ports:
      - "16379:6379"
    command: redis-server --appendonly yes
